services:
    - type: web
      name: mern-task-manager
      env: node
      buildCommand: npm install && npm run install-server && npm run install-client && npm run build
      startCommand: npm start
      envVars:
          - key: MONGODB_URI
            sync: false
          - key: NODE_ENV
            value: production
